# Intro to Pytorch Functions
An short introduction about PyTorch and about the chosen functions. 

- torch.tensor (To make a tensor array)
- torch.ones (To make a tensor of 1s) 
- torch.arange (To make a tensor from start to end with steps)
- torch.eye (To make a matrix with diagonal elements as 1s and rest as 0s)
- torch.sigmoid (To make sigmoid tensor of input tensor)

Before we begin, let's install and import PyTorch

In [1]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [2]:
# Import torch and other required modules
import torch

## Function 1 - torch.tensor (To make a tensor array)

Function to make tensors

In [2]:
# Example 1 - working (change this)
torch.tensor([[2, 2,5], [6,3, 4.]])

tensor([[2., 2., 5.],
        [6., 3., 4.]])

Example 1 is working because first and second array has same number of elements

In [3]:
# Example 2 - working
torch.tensor([[2, 2,5], [6,3, 4.], [2,2,3]])

tensor([[2., 2., 5.],
        [6., 3., 4.],
        [2., 2., 3.]])

Working since, same number of elements in each array

In [4]:
# Example 3 - breaking (to illustrate when it breaks)
torch.tensor([[1, 2], [3, 4, 5]])

ValueError: expected sequence of length 2 at dim 1 (got 3)

Example 3 is not working because the dimensions of the arrays are not same.

This function is used when we have to make a tensor (array)

Let's save our work using Jovian before continuing.

In [5]:
!pip install jovian --upgrade --quiet

In [6]:
import jovian

In [9]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ankitgadge250/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ankitgadge250/01-tensor-operations


'https://jovian.ai/ankitgadge250/01-tensor-operations'

## Function 2 - torch.ones

Returns a tensor filled with the scalar value 1, with the shape defined by the variable argument size.

In [9]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

A (2,3) dimensional array of ones is formed

In [10]:
torch.ones(10)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

A one dimensional array of 10 ones is formed

In [11]:
torch.ones(1,2.)

TypeError: ones(): argument 'size' must be tuple of ints, but found element of type float at pos 2

The dimensions should be integer values. Floating pont number breaks the function

We use this function when we have to initialize a vaector of ones during mathematical operations

In [12]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ankitgadge250/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ankitgadge250/01-tensor-operations


'https://jovian.ai/ankitgadge250/01-tensor-operations'

## Function 3 - torch.arange

Returns a tensor from start to end adding the steps

In [13]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

if only 1 input is present, then the tensor stars from 0 to input-1 and considering default step size as 1

In [15]:
torch.arange(1,8,.5)

tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000,
        5.5000, 6.0000, 6.5000, 7.0000, 7.5000])

This returns a tensor from the start to end-step with the step size as 0.5 (which is provided by us)

In [16]:
torch.arange(-2)

RuntimeError: upper bound and larger bound inconsistent with step sign

This function is helpful when we have to plot graphs 

In [17]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ankitgadge250/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ankitgadge250/01-tensor-operations


'https://jovian.ai/ankitgadge250/01-tensor-operations'

## Function 4 - torch.eye

This function returns a matrix with diagonal elements as 1 and the rest as 0s

In [19]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

A 4x4 diagonal matrix is formed with diagonal elements as 1

In [20]:
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

Here, the inputs as 3,4. So, a 3x4 matrix is formed in which 3x3 is a diagonal matrix and the 4th column has all zeroes

In [24]:
torch.eye(4,1.)

TypeError: eye() received an invalid combination of arguments - got (int, float), but expected one of:
 * (int n, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (int n, int m, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


The function recieves only integer values

This function is used in regressions for example to set w values

In [25]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ankitgadge250/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ankitgadge250/01-tensor-operations


'https://jovian.ai/ankitgadge250/01-tensor-operations'

## Function 5 - torch.sigmoid

This function returns the tensor of sigmoid values of input tensor.  output(i) = 1/(1 + e**(input(i))) 


In [37]:
a = torch.tensor([1.,2.,3.,4.])
torch.sigmoid(a)

tensor([0.7311, 0.8808, 0.9526, 0.9820])

The output is a sigmoid values of input

In [41]:
b = torch.tensor([[1.,2,3],[4,56,7]])
torch.sigmoid(b)

tensor([[0.7311, 0.8808, 0.9526],
        [0.9820, 1.0000, 0.9991]])

The sigmoid values of 2-D tensor is returned

In [43]:
c = torch.tensor([1,2,3])
torch.sigmoid(c)

RuntimeError: "sigmoid_cpu" not implemented for 'Long'

Sigmoid function is used only for floating point numbers and not for long ints

This function is used when we need to find sigmoid values while calculating gradient descent

In [44]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ankitgadge250/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ankitgadge250/01-tensor-operations


'https://jovian.ai/ankitgadge250/01-tensor-operations'

## Conclusion

In this notebook I learnt how to use documentation of pytorch. I learnt how to look at documentation to search for functions and implement them. 

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [46]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ankitgadge250/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ankitgadge250/01-tensor-operations


'https://jovian.ai/ankitgadge250/01-tensor-operations'

In [47]:
jovian.submit(assignment="zerotogans-a1")

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ankitgadge250/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ankitgadge250/01-tensor-operations
[jovian] Submitting assignment..
[jovian] Verify your submission at https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/assignment/assignment-1-all-about-torch-tensor
